name: clip-factory-ci
services:
  postgres:
    ports: !override ['127.0.0.1:0:5432']
    volumes: !override []
  redis:
    command: [redis-server, --save, '']
    ports: !override ['127.0.0.1:0:6379']
    volumes: !override []
  minio:
    ports: !override ['127.0.0.1:0:9000', '127.0.0.1:0:9001']
    volumes: !override []
  temporal:
    ports: !override ['127.0.0.1:0:7233']
  temporal-ui:
    profiles: [ui]
volumes: {}
