export type AIUsageEventRecordDto = {
  id: string;
  projectId: string;
  analysisRunId: string;
  clipId: string | null;
  providerResponseId: string;
  requestHash: string;
  purpose: string;
  modelId: string;
  reasoning: string;
  promptVersion: string;
  schemaVersion: string;
  pricingVersion: string;
  inputTokens: number;
  cachedInputTokens: number;
  cacheWriteInputTokens: number;
  outputTokens: number;
  reasoningTokens: number;
  pricingTier: string;
  costMicrousd: bigint;
  occurredAt: Date;
};
