import type { AIUsageEventEntityDto } from '../../../application/dto/entity';
import type { AIUsageEventRecordDto } from '../dto/record/ai-usage-event-record.dto';
export const aiUsageEventRecordToEntity = (
  r: AIUsageEventRecordDto,
): AIUsageEventEntityDto => ({
  id: r.id,
  projectId: r.projectId,
  analysisRunId: r.analysisRunId,
  clipId: r.clipId,
  providerResponseId: r.providerResponseId,
  requestHash: r.requestHash,
  purpose: r.purpose,
  modelId: r.modelId,
  reasoning: r.reasoning,
  promptVersion: r.promptVersion,
  schemaVersion: r.schemaVersion,
  pricingVersion: r.pricingVersion,
  cachedInputTokens: BigInt(r.cachedInputTokens),
  cacheWriteInputTokens: BigInt(r.cacheWriteInputTokens),
  outputTokens: BigInt(r.outputTokens),
  reasoningTokens: BigInt(r.reasoningTokens),
  pricingTier: r.pricingTier,
  costMicrousd: r.costMicrousd,
  occurredAt: r.occurredAt,
  totalInputTokens: BigInt(r.inputTokens),
  responseObjectReference: null,
  reservationCallId: null,
  reservationProjectId: null,
  reservationAnalysisRunId: null,
});
export const aiUsageEventEntityToRecord = (
  e: Omit<AIUsageEventEntityDto, 'id'>,
): Omit<AIUsageEventRecordDto, 'id'> => ({
  projectId: e.projectId,
  analysisRunId: e.analysisRunId,
  clipId: e.clipId ?? null,
  providerResponseId: e.providerResponseId,
  requestHash: e.requestHash,
  purpose: e.purpose,
  modelId: e.modelId,
  reasoning: e.reasoning,
  promptVersion: e.promptVersion,
  schemaVersion: e.schemaVersion,
  pricingVersion: e.pricingVersion,
  inputTokens: Number(e.totalInputTokens),
  cachedInputTokens: Number(e.cachedInputTokens),
  cacheWriteInputTokens: Number(e.cacheWriteInputTokens),
  outputTokens: Number(e.outputTokens),
  reasoningTokens: Number(e.reasoningTokens),
  pricingTier: e.pricingTier,
  costMicrousd: e.costMicrousd,
  occurredAt: e.occurredAt,
});
